using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;

namespace RunCPU
{
    class Generator
    {
        static string[] names = new[]
        {
            "Jacob",
            "Michael",
            "Joshua",
            "Matthew",
            "Ethan",
            "Andrew",
            "Daniel",
            "Anthony",
            "Christopher",
            "Joseph",
            "William",
            "Alexander",
            "Ryan",
            "David",
            "Nicholas",
            "Tyler",
            "James",
            "John",
            "Jonathan",
            "Nathan",
            "Samuel",
            "Christian",
            "Noah",
            "Dylan",
            "Benjamin",
            "Logan",
            "Brandon",
            "Gabriel",
            "Zachary",
            "Jose",
            "Elijah",
            "Angel",
            "Kevin",
            "Jack",
            "Caleb",
            "Justin",
            "Austin",
            "Evan",
            "Robert",
            "Thomas",
            "Luke",
            "Mason",
            "Aidan",
            "Jackson",
            "Isaiah",
            "Jordan",
            "Gavin",
            "Connor",
            "Aiden",
            "Isaac",
            "Jason",
            "Cameron",
            "Hunter",
            "Jayden",
            "Juan",
            "Charles",
            "Aaron",
            "Lucas",
            "Luis",
            "Owen",
            "Landon",
            "Diego",
            "Brian",
            "Adam",
            "Adrian",
            "Kyle",
            "Eric",
            "Ian",
            "Nathaniel",
            "Carlos",
            "Alex",
            "Bryan",
            "Jesus",
            "Julian",
            "Sean",
            "Carter",
            "Hayden",
            "Jeremiah",
            "Cole",
            "Brayden",
            "Wyatt",
            "Chase",
            "Steven",
            "Timothy",
            "Dominic",
            "Sebastian",
            "Xavier",
            "Jaden",
            "Jesse",
            "Devin",
            "Seth",
            "Antonio",
            "Richard",
            "Miguel",
            "Colin",
            "Cody",
            "Alejandro",
            "Caden",
            "Blake",
            "Carson",
            "Kaden",
            "Jake",
            "Henry",
            "Liam",
            "Victor",
            "Riley",
            "Ashton",
            "Patrick",
            "Bryce",
            "Brady",
            "Vincent",
            "Trevor",
            "Tristan",
            "Mark",
            "Jeremy",
            "Oscar",
            "Marcus",
            "Jorge",
            "Parker",
            "Kaleb",
            "Cooper",
            "Kenneth",
            "Garrett",
            "Joel",
            "Ivan",
            "Josiah",
            "Alan",
            "Conner",
            "Eduardo",
            "Paul",
            "Tanner",
            "Braden",
            "Alexis",
            "Edward",
            "Omar",
            "Nicolas",
            "Jared",
            "Peyton",
            "George",
            "Maxwell",
            "Cristian",
            "Francisco",
            "Collin",
            "Nolan",
            "Preston",
            "Stephen",
            "Ayden",
            "Gage",
            "Levi",
            "Dakota",
            "Micah",
            "Eli",
            "Manuel",
            "Grant",
            "Colton",
            "Damian",
            "Ricardo",
            "Giovanni",
            "Andres",
            "Emmanuel",
            "Peter",
            "Malachi",
            "Cesar",
            "Javier",
            "Max",
            "Hector",
            "Edgar",
            "Shane",
            "Fernando",
            "Ty",
            "Jeffrey",
            "Bradley",
            "Derek",
            "Travis",
            "Brendan",
            "Shawn",
            "Edwin",
            "Spencer",
            "Mario",
            "Dalton",
            "Erick",
            "Johnathan",
            "Erik",
            "Jonah",
            "Donovan",
            "Leonardo",
            "Wesley",
            "Elias",
            "Marco",
            "Trenton",
            "Devon",
            "Brody",
            "Abraham",
            "Jaylen",
            "Bryson",
            "Josue",
            "Sergio",
            "Drew",
            "Damien",
            "Raymond",
            "Andy",
            "Dillon",
            "Gregory",
            "Roberto",
            "Roman",
            "Martin",
            "Andre",
            "Jace",
            "Oliver",
            "Miles",
            "Harrison",
            "Jalen",
            "Corey",
            "Dominick",
            "Avery",
            "Clayton",
            "Pedro",
            "Israel",
            "Calvin",
            "Colby",
            "Dawson",
            "Cayden",
            "Jaiden",
            "Taylor",
            "Landen",
            "Troy",
            "Julio",
            "Trey",
            "Jaxon",
            "Rafael",
            "Dustin",
            "Ruben",
            "Camden",
            "Frank",
            "Scott",
            "Mitchell",
            "Zane",
            "Payton",
            "Kai",
            "Keegan",
            "Skyler",
            "Brett",
            "Johnny",
            "Griffin",
            "Marcos",
            "Derrick",
            "Drake",
            "Raul",
            "Kaiden",
            "Gerardo"
        };

        public static Reservation[] GetReservation(int count)
        {
            var r = new Random();

            return Enumerable.Range(0, count)
                .Select(i =>
                {
                    var checkIn = DateTime.UtcNow.AddDays(r.Next(100, 200));
                    var name = names[r.Next(0, names.Length)];
                    return new Reservation()
                    {
                        ReservationId = r.Next(0, 1000000),
                        Room = new Room()
                        {
                            RoomId = r.Next(0, 1000000),
                            Number = r.Next(100, 999),
                            Price = r.Next(50, 10000)
                        },
                        DateCreated = DateTime.UtcNow.AddDays(r.Next(0, 100)),
                        CheckIn = checkIn,
                        CheckOut = checkIn.AddDays(r.Next(0, 30)),
                        Guests = r.Next(1, 5),
                        Traveler = new Traveler()
                        {
                            TravelerId = r.Next(0, 1000000),
                            Name = name,
                            Email = $"{name.ToLower()}+{r.Next(1, 1000)}@hotmail.com"
                        }
                    };
                })
            .ToArray();
        }
    }
}
